version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on: 
      - db

  db:
    image: mysql
    restart: always
    environment: 
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - .dbdate:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports: 
      - 3306:3306

  
  front:
    build:
      context: .
      dockerfile: Dockerfile_react
    restart: always
    volumes:
      - ./node:/usr/src/app:cached
    command: sh -c "cd django_front && yarn start"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    #stdin_open: true