# Generated by Django 3.1.3 on 2022-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wetherdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('prefecture', models.CharField(max_length=10, verbose_name='観測地点')),
                ('maxtemp', models.IntegerField(verbose_name='最高気温')),
                ('mintemp', models.IntegerField(verbose_name='最低気温')),
                ('precipitation', models.IntegerField(verbose_name='降水量')),
                ('snowfall', models.IntegerField(verbose_name='積雪量')),
                ('summary', models.CharField(max_length=15, verbose_name='天気概要')),
            ],
        ),
    ]
